spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl
    username: kyee
    password: kyeepass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true